logging:
  level:
    root: WARN

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:pages
    driver-class-name: org.h2.Driver
    username: user
    password:


server:
  address: 0.0.0.0

